In [6]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
### sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
## Define the vocabulary size
voc_size=10000

In [10]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4591, 5743, 4838, 6661],
 [4591, 5743, 4838, 6791],
 [4591, 8289, 4838, 182],
 [6152, 6495, 5016, 6381, 202],
 [6152, 6495, 5016, 6381, 9043],
 [7191, 4591, 1447, 4838, 5995],
 [7089, 1122, 5847, 6381]]

In [11]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4591 5743 4838 6661]
 [   0    0    0    0 4591 5743 4838 6791]
 [   0    0    0    0 4591 8289 4838  182]
 [   0    0    0 6152 6495 5016 6381  202]
 [   0    0    0 6152 6495 5016 6381 9043]
 [   0    0    0 7191 4591 1447 4838 5995]
 [   0    0    0    0 7089 1122 5847 6381]]


In [14]:
## feature representation
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 196ms/step


array([[[-0.01934135, -0.01610101, -0.02029886,  0.02019732,
         -0.01887401,  0.01088829, -0.01838963, -0.01353487,
          0.0458113 ,  0.03699126],
        [-0.01934135, -0.01610101, -0.02029886,  0.02019732,
         -0.01887401,  0.01088829, -0.01838963, -0.01353487,
          0.0458113 ,  0.03699126],
        [-0.01934135, -0.01610101, -0.02029886,  0.02019732,
         -0.01887401,  0.01088829, -0.01838963, -0.01353487,
          0.0458113 ,  0.03699126],
        [-0.01934135, -0.01610101, -0.02029886,  0.02019732,
         -0.01887401,  0.01088829, -0.01838963, -0.01353487,
          0.0458113 ,  0.03699126],
        [-0.04465747, -0.00512765,  0.0029876 ,  0.02618852,
          0.04568895,  0.01125402,  0.03070053,  0.0119433 ,
         -0.01321781, -0.02770518],
        [-0.03928089, -0.02423862,  0.04542055, -0.0470211 ,
         -0.03858368, -0.03446114,  0.02774981, -0.01204447,
          0.01838719,  0.0162833 ],
        [-0.04794444, -0.03998208,  0.0137932 ,  0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 4591, 5743, 4838, 6661])

In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 43ms/step


array([[-0.01934135, -0.01610101, -0.02029886,  0.02019732, -0.01887401,
         0.01088829, -0.01838963, -0.01353487,  0.0458113 ,  0.03699126],
       [-0.01934135, -0.01610101, -0.02029886,  0.02019732, -0.01887401,
         0.01088829, -0.01838963, -0.01353487,  0.0458113 ,  0.03699126],
       [-0.01934135, -0.01610101, -0.02029886,  0.02019732, -0.01887401,
         0.01088829, -0.01838963, -0.01353487,  0.0458113 ,  0.03699126],
       [-0.01934135, -0.01610101, -0.02029886,  0.02019732, -0.01887401,
         0.01088829, -0.01838963, -0.01353487,  0.0458113 ,  0.03699126],
       [-0.04465747, -0.00512765,  0.0029876 ,  0.02618852,  0.04568895,
         0.01125402,  0.03070053,  0.0119433 , -0.01321781, -0.02770518],
       [-0.03928089, -0.02423862,  0.04542055, -0.0470211 , -0.03858368,
        -0.03446114,  0.02774981, -0.01204447,  0.01838719,  0.0162833 ],
       [-0.04794444, -0.03998208,  0.0137932 ,  0.00557815,  0.0306358 ,
         0.0410238 ,  0.03456542,  0.01443918